@@include('../libs/jquery/dist/jquery.js')
@@include('../libs/bootstrap/dist/js/bootstrap.js')
@@include('../libs/owl.carousel/dist/owl.carousel.js')

@@include('../libs/jquery-ui/ui/version.js')
@@include('../libs/jquery-ui/ui/safe-active-element.js')
@@include('../libs/jquery-ui/ui/escape-selector.js')
@@include('../libs/jquery-ui/ui/form.js')
@@include('../libs/jquery-ui/ui/widget.js')
@@include('../libs/jquery-ui/ui/position.js')
@@include('../libs/jquery-ui/ui/form-reset-mixin.js')
@@include('../libs/jquery-ui/ui/keycode.js')
@@include('../libs/jquery-ui/ui/labels.js')
@@include('../libs/jquery-ui/ui/unique-id.js')
@@include('../libs/jquery-ui/ui/widgets/menu.js')
@@include('../libs/jquery-ui/ui/widgets/selectmenu.js')
@@include('../libs/jquery-ui/ui/widgets/mouse.js')
@@include('../libs/jquery-ui/ui/widgets/slider.js')